### ISSUE TITLE
Incorrect run type in UI?

### ISSUE THREAD

**Issue by swinner95** [Azure/azureml-previews#114]
why is the run type for a job 'Script'? should it be command or sweep job?

AB#994197

**Comment by rihorn2** [comment]
To clarify, this is in the AzureML portal UI?

Sweep jobs are listed as hyperdrive and command jobs are listed as script.
Under the hood, command jobs are azureml.scriptrun jobs, this enum is shown as 'Script' in the UI.

**Comment by swinner95** [comment]
yes in the AML portal UI, thanks for clarifying. would it make more sense for the script runs to be renamed to command jobs?

**Comment by paulshealy1** [comment]
@swinner95 yes.
