### ISSUE TITLE
Schema hosting for various clouds

### ISSUE THREAD

**Issue by yanrez** [Azure/azureml-previews#122]
Currently schema is hosted on blob in public cloud https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json

We need to setup a plan for how this will work in various clouds - those shouldn't depend on public cloud. Also in various network isolation scenarios so customers can configure a highly locked down egress in their networks. We probably need to get this hosted on aml domain / have release process across clouds

AB#995493

**Comment by rihorn2** [comment]
@yanrez for private clouds, the highly locked down scenario, is the plan to bundle the schemas into the VSCode extension sufficient? In general, it seems valuable to have what's currently in the public cloud available for showing the current state of the dev repo, but how should we store/version the schema for a given cli version?

**Comment by yanrez** [comment]
@jpe316 do you remember what's the plan for this? I think we discussed this with extension team.

Schema in public cloud is totally valuable, I just want to make sure we have proper experience for people in other environments. Imagine using samples that refer to public cloud schema and not able to get intelisense work right away until you go and string replace line in every json file in the repo :(

**Comment by SiddhanthUnnithan** [comment]
@yanrez Brandon and I have talked about how this would work for users in other environments. The tentative plan is for the extension to be bundled with the schemas when published to the VS Code marketplace. Given that the user has the extension installed when they open up a sample that has a reference to a public cloud schema the extension will check to see whether the schema is accessible and if not, it will fall back to using the schemas it has been bundled with.

**Comment by SiddhanthUnnithan** [comment]
The obvious caveat here is that users in air-gapped environments will have access to the schema version that's part of the bundle. If there are changes made to the schema between extension release dates, said users will have to wait for the next release. I guess this would be solved if we ship a new version of the extension each time the schema is updated, but depending on the frequency of that it may not be feasible.

**Comment by SiddhanthUnnithan** [comment]
From the extension perspective we never want the user to have to manually add schemas to their VS Code workspace (and mappings in settings.json). We should always be providing them with static and dynamic completion options. We've spoken to @danielsc about this and will be prioritizing air-gapped support in the upcoming months (as the work gets closer to GA).

**Comment by yanrez** [comment]
Makes sense. I think having a bit of delay between schema updates and extension release cadence won't be a big problem
