### ISSUE TITLE
CommandJob has contaminated stdout

### ISSUE THREAD

**Issue by yanrez** [Azure/azureml-previews#123]
AML should have a log file containing raw stdout, and another log file containing raw stderr. Any infra/platform logs should go into separate log file. Once command job gets clean room implementation, let's use this as opportunity to fix the log mess in driver_log.

See example below where my stdout has 1 line i printed, everything else is not my code.

![image](https://user-images.githubusercontent.com/13227295/102846328-8b9e7200-43c4-11eb-82dd-2386141502f2.png)

AB#995495

**Comment by jpe316** [comment]
@wenxwei

**Comment by metazool** [comment]
Not sure if it's worth raising a separate issue, but when streaming logs from `az ml job stream` it would be hugely helpful to see STDERR in the output as well as STDOUT (I see it in the integrated log view in the web UI, but not in the output from `job stream`)
