### ISSUE TITLE
'az ml environment show' doesn't support environment notation used by job yml

### ISSUE THREAD

**Issue by yanrez** [Azure/azureml-previews#126]
In job yaml i put 'azureml:' prefix, but in 'az ml environment show' i can't. 

```
❯ az ml environment show --name azureml:AzureML-Minimal
Command group 'ml environment' is experimental and not covered by customer support. Please use with discretion.
ResourceNotFoundError: (UserError) No definitions exist for environment azureml:AzureML-Minimal
```

AB#995850

**Comment by luigiw** [comment]
Yeah, this is because azureml:AzureML-Minimal is actually not the name, rather it's a pointer, it translates to the full arm id in a given ws when the job is created.

**Comment by yanrez** [comment]
I understand translation. My point that as user I expect being able to copy last exact same string between yaml and cli and work in both places

**Comment by luigiw** [comment]
I get that, but even in yaml there's difference between pointer and name, see examples below

1)
environment: azureml:AzureML-Minimal

2)
environment:
  name: bla
  version: 1
  conda_fie: file:./conda.yaml

in the first case "azureml:AzureML-Minimal" is a point to an environment but not the name, in the second case, name is specified as part of environment definition.
