### ISSUE TITLE
Introduce shorthand --web to give studio URI

### ISSUE THREAD

**Issue by jpe316** [Azure/azureml-previews#138]
![image](https://user-images.githubusercontent.com/10729578/104504662-a3b67b00-5597-11eb-9380-ef42489f03cb.png)
 
Instead of needing to learn where it is. Feedback from @AbeOmor 

AB#1009452

**Comment by lostmygithubaccount** [comment]
should (and can) it auto-open in browser? that is the behavoir of `gh * view --web`

**Comment by Damovisa** [comment]
I'd vote no for auto-opening. CLI is often used in a non-interactive mode (e.g. GitHub Actions) where auto open doesn't make sense.

`--web` doesn't feel descriptive enough to me...

Would adding to the `--output` / `-o` options be appropriate?
i.e.
`az ml job create --file examples/iris/iris-job.yml --name iris_$GITHUB_RUN_ID --output url`

**Comment by lostmygithubaccount** [comment]
``--web`` auto-opening the browser in the ``gh`` CLI is, hands down, the most useful thing I have used in a CLI tool. and I think makes *even more sense* for data scientists/developers using Azure ML 

which brings me to a meta-point I haven't been able to express well - we're building both an Azure service and a data science framework, and they don't mesh well together. I think we need some separation between the two, but I'm not sure how.

But back to this topic, I agree ``--web`` would be weird to use in CI/CD, but that's not the intention here - it's intended for use like ``gh * view --web``. this is incredibly useful for kicking off a PR or an issue from the terminal is VSCode, then immediately opening it in the GitHub UI (usually in my browser which is in fullscreen split mode with VSCode) where you can more easily do things like add labels, view the status of checks, etc.. this translates directly to the Azure ML, where after kicking off a job I usually want to go watch the compute target, logs, etc. in a better UI (similar to having a notebook widget, which would be hard to replicate in CLI)

So completely agree with also having ``-o``, but I think we should really target ``--web`` or ``-w`` like ``gh`` does for this functionality for interactive data science

**Comment by Damovisa** [comment]
Yep, totally fair. I think this is two different things then?

`--web` would behave just like the `gh` CLI and open the in the browser.
`-o` would let you specify the output as just the studio URL.
