### ISSUE TITLE
az ml workspace delete does not delete other Azure resources

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-previews#240]
## Describe the issue

description:

## Minimal example

```
az ml workspace create --name testing --resource-group azureml-examples
az ml workspace delete --name testing --resource-group azureml-examples
```

This will create the Workspace, Storage Account, Key Vault, etc. but the delete does not get rid of the resources

## Additional context

-

AB#1122990

**Comment by mx-iao** [comment]
That is by design. You need to use the `--dependent-resources` flag.

**Comment by lostmygithubaccount** [comment]
I see - the flag is named `--all-resources` (at least right now)

![image](https://user-images.githubusercontent.com/54814569/113621283-4ff48480-9610-11eb-848f-0aa9da89d5fa.png)

**Comment by lostmygithubaccount** [comment]
reopening - should this not be the default? it's kinda weird to see this:

```
az ml workspace create --name testing --resource-group azureml-examples
az ml workspace delete --name testing --resource-group azureml-examples
```

and have a bunch of Azure resources hanging around
