### ISSUE TITLE
creating a minimal job via CLI

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-previews#246]
## Describe the issue

description: I want to create a minimal job with the `az ml job create` command

first, I run `az ml job create -h` to see what it requires:

![image](https://user-images.githubusercontent.com/54814569/113622060-4fa8b900-9611-11eb-9884-74efd09522b2.png)

only workspace name and resource group? suspicious:

trying it out, it says "compute is required" despite not showing up in the -h command:

![image](https://user-images.githubusercontent.com/54814569/113622138-65b67980-9611-11eb-9005-16a6b084b79d.png)

trying to manually `--set compute=cpu-cluster` fails too:

![image](https://user-images.githubusercontent.com/54814569/113622178-7666ef80-9611-11eb-91dc-64309edcb58b.png)

## Minimal example

```
az ml ...
```

## Additional context

-

AB#1123190

**Comment by mx-iao** [comment]
`--file` should be required for az ml job. Will open a bug for that. Will also track a bug to make error message more clear the missing fields are for the yaml file.

**Comment by harneetvirk** [comment]
--file has been updated as required in the command: az ml job -h
![image](https://user-images.githubusercontent.com/20194110/114929072-33aecf80-9de8-11eb-8a60-15abc773220d.png)
