### ISSUE TITLE
`az ml environment` usability

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-previews#248]
## Describe the issue

description:

Listing all environments with `-o table` prints out the name and resource group - resource group is redundant since it seems required: 

![image](https://user-images.githubusercontent.com/54814569/113630557-ec248880-961c-11eb-952e-6a980c310889.png)

after listing, I see one I want to delete:

![image](https://user-images.githubusercontent.com/54814569/113630607-fe062b80-961c-11eb-8dc1-0b7ab1bb2661.png)

it seems deleting an asset is by version, which I would a) not expect b) hope to see listed in the `list` command if so

![image](https://user-images.githubusercontent.com/54814569/113630691-25f58f00-961d-11eb-8b03-e9ca4cf6065e.png)

after guessing the only version is "1", I can now delete that environment and it will now show up in my list

AB#1123326

**Comment by lostmygithubaccount** [comment]
also seems like I can't delete the AzureML environments, it says "UserError" - messaging could be more clear

![image](https://user-images.githubusercontent.com/54814569/113631087-c481f000-961d-11eb-83b6-6d0c527eb54c.png)

**Comment by mx-iao** [comment]
You can only delete a specific version of an asset

**Comment by lostmygithubaccount** [comment]
I don't think users will find this intuitive
