### ISSUE TITLE
InternalServerError when mounting dataset via CLI

### ISSUE THREAD

**Issue by metazool** [Azure/azureml-previews#258]
## Describe the issue

Previously working YAML configuration for the v2 preview CLI is now failing with an empty `InternalServerError` response.
On removing the `inputs` section from the job configuration, the error doesn't trigger (but the job now has no inputs!)

## Minimal example

```
az ml job create --file test.yml
```

With an `inputs` section that looks like this (the dataset name and contents verified to exist, with configuration unchanged from previously working runs)

```
inputs:
  training_data:
    data: azureml:Sample_Data:1
    mode: mount
```

Throws the following error (via `az ml job stream -n [id]`)

```
Exception :
 {
    "error": {
        "code": "ServiceError",
        "message": "InternalServerError",
        "details": []
    },
    "correlation": {
        "operation": null,
        "request": "...id..."
    },
    "environment": "northeurope",
    "location": "northeurope",
    "time": "2021-04-12T09:18:37.031948Z"
}
```

AB#1130518

**Comment by lostmygithubaccount** [comment]
also started seeing this, team is investigating
