### ISSUE TITLE
UserError when using `az ml job` subcommand

### ISSUE THREAD

**Issue by shwars** [Azure/azureml-previews#267]
## Describe the issue

When using `az ml job list`, `az ml job show`, `az ml job download`, `az ml job stream`, etc. the same error is displayed:

```
Code: UserError
Message: Job nertrain not found.
```
(the last line is shown for commands that require specifying job name using `-n`). The job (experiment) with specified name (`nertrain`) exists. `az ml job create -f` works perfectly.

## Additional context

- az ml version: 0.0.67
- azure cli: 2.22.1

AB#1141831

**Comment by lostmygithubaccount** [comment]
the job name is not the same as the experiment name - if you did not provide a `name:` in the YAML file a GUID is created for the job name, which you need to use after `-n`

**Comment by lostmygithubaccount** [comment]
you may want to capture the job name when you submit it like this:

```
job_id=`az ml job create -f path/to/job.yml`
...
az ml job show -n $job_id --web
```

**Comment by shwars** [comment]
@lostmygithubaccount Thanks so much for the clarification! I am still getting an error for `job list`:
```
Code: UserError
Message: Cannot create a run with runId=KeraGAN_1583245606_b0470c52 and experimentId=2455d43a-0f95-4878-bcd8-3e9035728c14. As a run with runId = KeraGAN_1583245606_b0470c52 and experimentId=aef53485-834c-41c6-8b65-05d12e4db300 already exists in the workspace.
```
Looks like it has something to do with one of the old experiements I have created from Python SDK, but I thought I will still share the error.

**Comment by lostmygithubaccount** [comment]
how are you defining the job name? if manually, you cannot reuse the same one

**Comment by shwars** [comment]
> how are you defining the job name? if manually, you cannot reuse the same one

I am using GUID, and show/download/stream commands work for me now (with the exception that stream does not do live streaming, just displays the current log and stops). It is `job list` that does not work.

**Comment by mrudulan** [comment]
Hey @shwars are we seeing this error for job list of job create?
